### ISSUE TITLE
Random image at registration fails

### ISSUE THREAD

**Issue by dmseaton** [cuonoj/harrySlynx#2]
Half of the test users don't have a random image assigned, please fix

**Comment by cuonoj** [comment]
this is really trick.. I try to figure out a couple of times but unsuccessful. and I rewrite on side and see line 23 'tt_register_image'
very trick. so I declare ', WP_User $user' for ensuring all new users have an image assigned
I try to test but really not sure if is this the better approach for a solution.

**Comment by dmseaton** [comment]
Is it maybe to do with the API itself?

**Comment by dmseaton** [comment]
This issue is still outstanding - the commit is for a different ticket!

**Comment by cuonoj** [comment]
apologies.
about this issue, to be honest, I try to figure out this now in different ways but I don't realize. sorry!
